CREATE TABLE countries (
  code VARCHAR(10) NOT NULL PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  "group" VARCHAR(20) NOT NULL,
  states TEXT NOT NULL);
CREATE TABLE cities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(40) NOT NULL,
  country VARCHAR(10) NOT NULL,
  lat DOUBLE NOT NULL,
  lng DOUBLE NOT NULL,
  FOREIGN KEY (country) REFERENCES countries (code));